#!/usr/bin/env bash
set -e

OUTPUT_DIR=/tmp/connect-ipa

usage () { popd > /dev/null; echo "deploy <acceptance|production>"; exit 1; }

if [ "$#" -ne 1 ]; then
  usage
fi

pushd "src/Connect" > /dev/null

mkdir -p OUTPUT_DIR

if [ "$1" = "acceptance" ]; then
  echo "Archiving and delivering to acceptance..."
  gym -q Acceptance -o "$OUTPUT_DIR"
elif [ "$1" = "production" ]; then
  echo "Archiving and delivering to production..."
  gym -q Release -o "$OUTPUT_DIR"
else
  usage
fi

pushd "$OUTPUT_DIR"

deliver --ipa "Bernie Connect.ipa" --username "mikestallard@gmail.com" --team_id 118153786 --skip_screenshots --force
echo "Done!"

popd > /dev/null
popd > /dev/null
