#!/bin/bash

export SCRIPT_DIR=$(dirname "$0")

##
## Build Process
##

main ()
{
    cd src/Movement 
    carthage bootstrap --platform iphonesimulator --no-use-binaries
    xctool clean build -project Movement.xcodeproj/ -target Movement -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 2>/dev/null
    xcodebuild test -project Movement.xcodeproj/ -target Movement -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 2>/dev/null

    local status=$?

    exit $status
}

main
